apiVersion: v1
kind: Secret
metadata:
  name: axes-production-config
type: Opaque
stringData:
  production.toml: |
    [pg]
    write_url = "postgresql://postgres:password@pg_host:5432/db_name"
    read_url = "postgresql://postgres:password@pg_host:5433/db_name"

    [redis]
    url = "redis://redis:6379/"
