//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use serde::Deserialize;

pub mod prelude;

pub mod bakery;
pub mod chef;
pub mod todo_items;

#[derive(Deserialize)]
pub struct Params {
    pub page: Option<u64>,
    pub size: Option<u64>,
}
