//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::bakery::Entity as Bakery;
pub use super::chef::Entity as Chef;
pub use super::cities::Entity as Cities;
pub use super::weather::Entity as Weather;
