//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "TodoItems")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "Name")]
    pub name: String,
    #[sea_orm(column_name = "IsComplete")]
    pub is_complete: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
